[build]
  command = "node build-static.js"
  publish = "dist"

[[redirects]]
  from = "https://www.disfracesperu.net.pe/*"
  to = "https://disfracesperu.net.pe/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/data"
  to = "/data/db.json"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/"
  status = 302
